// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrw2-wNusG2fQklE-xWfJsRtPw4ilTCgc',
    appId: '1:547009831938:web:6ea262059f1a0cfb2af31b',
    messagingSenderId: '547009831938',
    projectId: '',
    authDomain: '',
    storageBucket: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAej5vjpWqgPCzSFFsOLvQH7clmcoefGWc',
    appId: '1:547009831938:android:9ac8270fc9e94df92af31b',
    messagingSenderId: '547009831938',
    projectId: '',
    storageBucket: '',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAurw1-Kh-jKSp_7iVp29UbiweeldIUFyg',
    appId: '1:547009831938:ios:7ce43f30c56943fa2af31b',
    messagingSenderId: '547009831938',
    projectId: '',
    storageBucket: '',
    iosClientId: '547009831938-i5v19toe6cq8kptfvu0p6fdi73apjcfi.apps.googleusercontent.com',
    iosBundleId: '',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAurw1-Kh-jKSp_7iVp29UbiweeldIUFyg',
    appId: '1:547009831938:ios:64261852bd40b28c2af31b',
    messagingSenderId: '547009831938',
    projectId: '',
    storageBucket: '',
    iosClientId: '',
    iosBundleId: '',
  );
}
